

window.subtitles = [
  { text: "In his first solo exhibition with Upstream Gallery,"},
  { text: "Harm van den Dorpel features works from multiple series'"},
  { text: "that react to different moments in the history of cybernetics." },
  { text: "Pattern and Presence, the title of the show,"},
  { text: "is taken from the book 'How we became posthuman'" },
  { text: "by N. Katherine Hayles (1999)," },
  { text: "in which she describes the historical development" },
  { text: "of cybernetics and politics of disembodiment." },
  { text: "Van den Dorpel employs various information technologies"},
  { text: "from this history of cybernetics in his artistic practice. " },
  { text: "He wants to demystify both the romantic notion of the 'artistic genius'"},
  { text: "as well as the 'black box' of computer algorithms," },
  { text: "which increasingly influence our personal lives" },
  { text:"and forecast our political future." },
  { text: "Where other traditional artistic mediums require the artist"},
  { text: "to create the work with their own hand, " },
  { text: "Van den Dorpel rather programs software and trains it"},
  { text: "by looping continuous feedback through its output" },
  { text: "in order to produce works with unpredictable aesthetic outcomes." },
  { text: "In this hybrid process, genetic properties are ascribed" },
  { text: "to the elements and composition that make up his artworks." },
  { text: "By selecting and crossbreeding across many generations," },
  { text: "\"optimal\" artworks emerge." },
  { text: "For this new series of printed transparent work"},
  { text: "(which is a continuation of his earlier series:"},
  { text: "\"Death Imitates Language\")"},
  { text: "Van den Dorpel focuses on the structure of 'nesting':" },
  { text: "a strong organizing principle found in architecture,"},
  { text: "software development and human language." },
  { text: "The artist draws on this system in order to compare"},
  { text: "the construction of language to the construction of artworks," },
  { text: "and in doing so, refers to the painterly question of how" },
  { text: "to fill the two-dimensional plane using composition and layering." },
  { text: "The genetic algorithms he uses," },
  { text: "originate from developments in computer science"},
  { text: "which emerged in the 1960s through to the 1980s and include:" },
  { text: "‘Turtle graphics' by Seymour Papert (late 1960s);"},
  { text: "research of feedback, reflexivity," },
  { text: "nesting and recursion (Autopoiesis, Varela & Maturana, 1972);"},
  { text: "and Artificial Life (Christopher Langton, 1986)." },
  { text: "Van den Dorpel also draws on recent developments in blockchain technology,"},
  { text: "specifically the Ethereum blockchain,"},
  { text: "in order to assign each work a unique identifier (a hash or fingerprint)." },
  { text: "This functions as a token which can be traded on the Ethereum blockchain"},
  { text: "and changes the status of the artwork to a form of currency" },
  { text: "– or a representation of itself – which circles back" },
  { text: "to the initial question of embodiment:" },
  { text: "are the works in fact the works?" },
  { text: "Or, are they representations of an external" },
  { text: "less material" },
  { text: "essence?" },
  { text: "Do we have a body or are we a body?" }
]
